build_failure_conditions:
    - 'elements.rating(<= D).new.exists'
    - 'issues.new.count > 10'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 9)'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.005)'
checks:
  php:
    verify_property_names: true
    verify_argument_usable_as_reference: true
    verify_access_scope_valid: true
    variable_existence: true
    useless_calls: true
    use_statement_alias_conflict: true
    use_self_instead_of_fqcn: true
    uppercase_constants: true
    unused_variables: true
    unused_properties: true
    unused_parameters: true
    unused_methods: true
    unreachable_code: true
    too_many_arguments: true
    switch_fallthrough_commented: true
    sql_injection_vulnerabilities: true
    single_namespace_per_use: false
    simplify_boolean_return: true
    side_effects_or_types: true
    security_vulnerabilities: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    require_scope_for_properties: true
    require_scope_for_methods: true
    require_php_tag_first: true
    psr2_switch_declaration: true
    psr2_class_declaration: true
    property_assignments: true
    prefer_while_loop_over_for_loop: true
    precedence_mistakes: true
    precedence_in_conditions: true
    phpunit_assertions: true
    php5_style_constructor: true
    parse_doc_comments: true
    parameters_in_camelcaps: true
    parameter_non_unique: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    overriding_private_members: true
    optional_parameters_at_the_end: true
    one_class_per_file: true
    non_commented_empty_catch_block: true
    no_unnecessary_if: true
    no_unnecessary_final_modifier: true
    no_underscore_prefix_in_properties: true
    no_underscore_prefix_in_methods: true
    no_trait_type_hints: true
    no_short_open_tag: true
    no_short_method_names:
        minimum: '3'
    no_property_on_interface: true
    no_non_implemented_abstract_methods: true
    no_goto: true
    no_global_keyword: true
    no_exit: true
    no_eval: true
    no_error_suppression: true
    no_empty_statements: true
    no_duplicate_arguments: true
    no_debug_code: true
    no_commented_out_code: true
    naming_conventions:
        local_variable: '^[a-z][a-zA-Z0-9_]*$'
        abstract_class_name: '^[A-Z][a-zA-Z0-9]*$'
        constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
        property_name: '^[a-z][a-zA-Z0-9_]*$'
        method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
        parameter_name: '^[a-z][a-zA-Z0-9]*$'
        interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
        type_name: '^[A-Z][a-zA-Z0-9]*$'
        exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
        isser_method_name: '^(?:is|has|should|may|supports)'
    more_specific_types_in_doc_comments: true
    missing_arguments: true
    method_calls_on_non_object: true
    instanceof_class_exists: true
    function_in_camel_caps: true
    foreach_usable_as_reference: true
    foreach_traversable: true
    fix_use_statements:
        remove_unused: true
        preserve_multiple: true
        preserve_blanklines: false
        order_alphabetically: false
    fix_doc_comments: false
    encourage_single_quotes: false
    encourage_shallow_comparison: true
    encourage_postdec_operator: true
    duplication: true
    deprecated_code_usage: true
    deadlock_detection_in_loops: true
    code_rating: true
    closure_use_not_conflicting: true
    closure_use_modifiable: true
    classes_in_camel_caps: true
    catch_class_exists: true
    blank_line_after_namespace_declaration: true
    avoid_useless_overridden_methods: true
    avoid_usage_of_logical_operators: true
    avoid_unnecessary_concatenation: true
    avoid_superglobals: true
    avoid_perl_style_comments: true
    avoid_multiple_statements_on_same_line: true
    avoid_length_functions_in_loops: true
    avoid_entity_manager_injection: true
    avoid_duplicate_types: true
    avoid_corrupting_byteorder_marks: true
    avoid_conflicting_incrementers: true
    avoid_closing_tag: true
    avoid_aliased_php_functions: true
    assignment_of_null_return: true
    argument_type_checks: true
    align_assignments: false

filter:
  paths:
    - src/*
  excluded_paths:
    - tests/*
    - vendor/*
build:
  environment:
    hosts:
      db: '127.0.0.1'
    mysql: 5.7
    php:
      version: 7.0.8
      ini:
        'date.timezone': 'UTC'
    redis: false
    postgresql: false

  dependencies:
    override:
      - composer install --no-interaction

  project_setup:
    before:
      - sudo mysql_upgrade --force
      - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS catalog_manager'
      - mysql -u root -e 'CREATE USER "catalog_manager"@"%" identified by "catalog_manager"'
      - mysql -u root -e 'GRANT ALL PRIVILEGES ON catalog_manager.* TO "catalog_manager"@"%"'

  tests:
    override:
      - command: vendor/bin/phpunit