language: php

services:
    - mysql

php:
    - '7.0'
    - '7.1'
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php:
            - hhvm
            - nightly

install:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

before_script:
    - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS catalog_manager'
    - mysql -u root -e 'CREATE USER "catalog_manager"@"%" identified by "catalog_manager"'
    - mysql -u root -e 'GRANT ALL PRIVILEGES ON catalog_manager.* TO "catalog_manager"@"%"'
    - bin/console doctrine:schema:update --force

after_success:
    - travis_retry php vendor/bin/coveralls