language: php

services:
    - mysql

php:
    - '7.0'
#    - '7.1'
#    - hhvm
#    - nightly

matrix:
    fast_finish: true
#    allow_failures:
#        - php: hhvm

mysql:
    database: travis_ci
    username: travis
    encoding: utf8

install:
    - composer install --no-interaction

before_script:
    - mysql -e 'CREATE DATABASE symfony;'
    - bin/console doctrine:schema:update --force
