language: php

php:
    - '7.0'
#    - '7.1'
#    - hhvm
#    - nightly

matrix:
    fast_finish: true
#    allow_failures:
#        - php: hhvm

mysql:
    database: symfony
    username: symfony
    password: symfony
    encoding: utf8

#before_install:
#    - sudo apt-get update > /dev/null

install:
#    - sudo apt-get install -y --force-yes php7.0-mysql
    - composer install --no-interaction

before_script:
    - mysql -uroot -p616012030 -e 'CREATE DATABASE symfony;'
    - mysql -uroot -p616012030 -e 'CREATE USER "symfony"@"localhost" IDENTIFIED BY "symfony";'
    - mysql -uroot -p616012030 -e 'GRANT ALL PRIVILEGES ON `symfony`.* TO "symfony"@"localhost";'
    - mysql -uroot -p616012030 -e 'FLUSH PRIVILEGES;'
