# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    tactician.commandbus.middleware:
#        - tactician.middleware.locking
        - "@tactician.middleware.command_handler"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    tactician.commandbus:
        class: League\Tactician\CommandBus
        arguments: ["%tactician.commandbus.middleware%"]
