# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    amd.query_bus:
        class: AMD\Common\Application\QueryBus
        arguments:
            - '@service_container'
    catalog.family_repository:
        class: AMD\Catalog\Infrastructure\Persistence\Doctrine\DoctrineFamilyRepository
        factory:
            - "@doctrine"
            - getRepository
        arguments: [ AMD\Catalog\Domain\Model\Family\Family ]
    catalog.product_repository:
        class: AMD\Catalog\Infrastructure\Persistence\Doctrine\DoctrineProductRepository
        factory:
            - "@doctrine"
            - getRepository
        arguments: [ AMD\Catalog\Domain\Model\Product\Product ]
    catalog.family.add_family_handler:
        class: AMD\Catalog\Application\Family\AddFamilyHandler
        arguments:
            - '@catalog.family_repository'
        tags:
            - { name: command_handler, handles: AMD\Catalog\Application\Family\AddFamilyCommand }
    catalog.family.update_family_handler:
        class: AMD\Catalog\Application\Family\UpdateFamilyHandler
        arguments:
            - '@catalog.family_repository'
        tags:
            - { name: command_handler, handles: AMD\Catalog\Application\Family\UpdateFamilyCommand }
    catalog.family.remove_family_handler:
        class: AMD\Catalog\Application\Family\RemoveFamilyHandler
        arguments:
            - '@catalog.family_repository'
        tags:
            - { name: command_handler, handles: AMD\Catalog\Application\Family\RemoveFamilyCommand }
    catalog.product.add_product_handler:
        class: AMD\Catalog\Application\Product\AddProductHandler
        arguments:
            - '@catalog.family_repository'
            - '@catalog.product_repository'
        tags:
            - { name: command_handler, handles: AMD\Catalog\Application\Product\AddProductCommand }
    catalog.product.update_product_handler:
        class: AMD\Catalog\Application\Product\UpdateProductHandler
        arguments:
            - '@catalog.family_repository'
            - '@catalog.product_repository'
        tags:
            - { name: command_handler, handles: AMD\Catalog\Application\Product\UpdateProductCommand }
    catalog.product.remove_product_handler:
        class: AMD\Catalog\Application\Product\RemoveProductHandler
        arguments:
            - '@catalog.product_repository'
        tags:
            - { name: command_handler, handles: AMD\Catalog\Application\Product\RemoveProductCommand }
    catalog.family.find_family_by_id_handler:
        class: AMD\Catalog\Application\Family\FindFamilyByIdHandler
        arguments:
            - '@catalog.family_repository'
        tags:
            - { name: amd.query_handler, handles: AMD\Catalog\Application\Family\FindFamilyByIdQuery }
    catalog.family.find_all_families_handler:
        class: AMD\Catalog\Application\Family\FindAllFamiliesHandler
        arguments:
            - '@catalog.family_repository'
        tags:
            - { name: amd.query_handler, handles: AMD\Catalog\Application\Family\FindAllFamiliesQuery }
    catalog.product.find_product_by_id_handler:
        class: AMD\Catalog\Application\Product\FindProductByIdHandler
        arguments:
            - '@catalog.product_repository'
        tags:
            - { name: amd.query_handler, handles: AMD\Catalog\Application\Product\FindProductByIdQuery }
    catalog.product.find_all_products_handler:
        class: AMD\Catalog\Application\Product\FindAllProductsHandler
        arguments:
            - '@catalog.product_repository'
        tags:
            - { name: amd.query_handler, handles: AMD\Catalog\Application\Product\FindAllProductsQuery }
