AMD\Catalog\Domain\Model\Product\Product:
    type: entity
    table: product
    repositoryClass: AMD\Catalog\Infrastructure\Persistence\Doctrine\DoctrineProductRepository
    id:
        id:
            type: ProductId
            id: true
    fields:
        description:
            type: string
            length: 255
        familyId:
            type: FamilyId
            column: family_id
    lifecycleCallbacks: {  }
