services:
    catalog.family.repository:
        class: AMD\Catalog\Infrastructure\Persistence\Doctrine\DoctrineFamilyRepository
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    catalog.add.family.service:
        class: AMD\Catalog\Application\AddFamilyService
        arguments: ["@catalog.family.repository"]
