services:
    catalog.family_repository:
        class: AMD\Catalog\Infrastructure\Persistence\Doctrine\DoctrineFamilyRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
    catalog.family.add_family_handler:
        class: AMD\Catalog\Application\Family\AddFamilyHandler
        arguments:
            - '@catalog.family_repository'
        tags:
            - { name: tactician.handler, command: AMD\Catalog\Application\Family\AddFamily }
