<?php
namespace AMD\Catalog\Infrastructure\Persistence\Doctrine;

use AMD\Catalog\Domain\Model\ProductRepository;

/**
 * DoctrineProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineProductRepository extends \Doctrine\ORM\EntityRepository implements ProductRepository
{
}
