<?php
namespace AMD\Catalog\Infrastructure\Persistence\Doctrine;

use AMD\Catalog\Domain\Model\FamilyRepository;

/**
 * DoctrineFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineFamilyRepository extends \Doctrine\ORM\EntityRepository implements FamilyRepository
{
}
